config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get 'pages/home' => 'pages#home'
  get 'pages/about' => 'pages#about'

  resources :articles
  resources :background_jobs

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/models/background_job.rb
class BackgroundJob < ActiveRecord::Base
  def self.start(id)
    find(id).start
  end

  def start
    @progress = 0

    while @progress<100
      sleep 1
      @progress += 10
      update_attribute(:progress, @progress)
    end

    update_attribute(:finished_at, Time.zone.now)

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "Article was successfully created!"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was successfully updated!"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end  

  def show
  end

  def edit
  end

  def destroy
    @article.destroy
    flash[:notice] = "Article was destroyed..."
    redirect_to articles_path
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description)
    end 

end

app/controllers/background_jobs_controller.rb
class BackgroundJobsController < ApplicationController

  def index
    @value = 0
    @jobs = BackgroundJob.all
    @newJob = BackgroundJob.new
  end

  def create
    create_job
  end

  def destroy
    @job = BackgroundJob.find(params[:id])
    @job.destroy
    flash[:notice] = @job.title + " job was destroyed..."
    redirect_to background_jobs_path
  end

  def show 
  end

  private

    def create_job
      @job = BackgroundJob.new(job_params)
      if @job.save
        flash[:success] = @job.title + " job created and started."
        @job.delay.start()
      else
        flash[:warning] = "Job creation error!"
      end

    redirect_to background_jobs_path

    end

    def job_params
      params.require(:background_job).permit(:title)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	
  def home
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(level)
    case level
      when 'notice' then "alert alert-info"
      when 'success' then "alert alert-success"
      when 'error' then "alert alert-danger"
      when 'warning' then "alert alert-warning"
    end
  end

end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <h2>The following errors prevent saving</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @article do |f| %>
  <p>
    <%= f.label :title %>
    <br/>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %>
    <br/>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to "Back", articles_path %>

app/views/articles/edit.html.erb
<h1>Edit existing article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>All articles</h1>
<p>
  <%= link_to "Create new article", new_article_path %>
</p>


<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td> <%= article.title %> </td>
      <td> <%= article.description %> </td>
      <td> <%= link_to "Edit", edit_article_path(article) %></td>
      <td> <%= link_to "Show", article_path(article) %></td>
      <td> <%= link_to "Delete", article_path(article), method: :delete, data: {confirm: "Are you sure?"} %>
    </tr>
  <% end %>


</table>

app/views/articles/new.html.erb
<h1>Create an article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Showing selected article</h1>

<p>
  Title : <%= @article.title %>
</p>

<p>
  Description : <%= @article.description %>
</p>

<%= link_to "Edit", edit_article_path(@article) %> | 
<%= link_to "Back", articles_path %>

app/views/background_jobs/index.html.erb
<div class="center jumbotron">
  
<h1>DELAYED JOB </h1>
  <div class="delayjob jumbotron">
    <p><b><%= @message%></b></p>
    
    <%= form_for(@newJob, :html => {:class => 'form-horizontal'}) do |job|%>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= job.label :title, "Title : " %>
        </div>
        <div class="col-sm-8">
          <%= job.text_field :title, class: "form-control", placeholder: "Please enter a new job name", autofocus: true %>
          <small id="jobNameHelp" class="form-text text-muted">After submit, the job will start process in the background.</small>
        </div>
      </div>
      <div class="form-group">
         <div class="col-sm-offset-2 col-sm-8">
          <%= job.submit "START", class: "btn btn-success" %>
        </div>
      </div>
    <% end %>

    <table class="table">
      <tr>
        <th scope="col">Job</th>
        <th scope="col">Progess</th>
      </tr>

      <% @jobs.each do |job| %>
        <tr>
          <td scope="row"> <%= job.title %> </td>
          <td>
            <div class="progress">
              <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" style="width: <%= job.progress%>%"><%= job.progress%>%</div>
            </div>
          </td>
          <td> 
            <%= link_to "Delete", background_job_path(job), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-warning" %>
          </td>
        </tr>
      <% end %>

    </table>

  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright &copy; Krittinun Sirodom
    </small>
    <nav>
      <ul>
        <li><%= link_to "About", pages_about_path %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="<%= flash_class(name) %>" align="center">
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--<a class="navbar-brand" id="logo" href="#">Alpha-blog</a>-->
      <%= link_to "Alpha blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!--<li><a href="#">Link <span class="sr-only">(current)</span></a></li>-->
        <li><%= link_to "Articles", articles_path%></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <!--<li><a href="#">Action</a></li>-->
            <li><%= link_to "New Article", new_article_path %></li> 
            <li role="separator" class="divider"></li>
            <li><%= link_to "Test Delay Job", background_jobs_path %></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Search</button>
      </form>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
  <div class="container">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>

</body>
</html>

app/views/pages/about.html.erb
<h1>ABOUT</h1>

<%= link_to image_tag('profile.jpg'), 'my Profile' %>

<ul>
  <li><%= link_to "HOME", pages_home_path %></li>
  <li><%= link_to "ARTICLE", articles_path %></li>
  <li><%= link_to "ABOUT", pages_about_path %></li>
</ul>

app/views/pages/home.html.erb
<div class="center jumbotron">
  
<h1>ALPHA BLOG</h1>
<%= link_to "Sign up now", "#", class: "btn btn-primary btn-sm" %>

</div>